# Сообщение, которое увидит игрок при нарушении
warning-message: "&cВаше сообщение кажется подозрительным!"

# Отменять ли подозрительное сообщение
cancel-message: true

# Права, которые позволяют обходить проверку
bypass-permissions:
  - "iriskantilang.bypass"